### ISSUE TITLE
Unnecessary duplicated types at Linx commerce App

### ISSUE THREAD

**Issue by viktormarinho** [deco-cx/apps#801]
Linx app types/ contains a lot of duplicated types, we should Merge those

**Comment by Samuel-Brito19** [comment]
Hi! Can you provide more information about the issue? I'm interest.

**Comment by viktormarinho** [comment]
@Samuel-Brito19 

The Linx app utils/types directory (https://github.com/deco-cx/apps/tree/main/linx/utils/types) currently contains a lot of those `JSON.ts` files. 

What happened here is that i used a tool that can generate typescript types from a JSON object (quicktype.io) to map every return of the Linx APIs.

So, for example, when creating the auctionDetail loader, i started by hitting the Linx Endpoint for auction details, copying the json response, pasting it into Quicktype then copying the generated TS Types to the project, putting it in the `auctionDetailJSON.ts` file. 

The problem here is that a lot of these types were shared between different endpoints, and i ended up having a bunch of duplicated types. I already started deduplicating some of those types, but there's a lot of duplicated ones still. For example, i created the `facets.ts` file and made it the only Facet interface in the linx types folder:

![Captura de Tela 2024-09-02 às 14 13 46](https://github.com/user-attachments/assets/5e103415-f140-45f7-a849-9b6db6de1f76)

Before, i had a lot of Facet types. But there are more types that can be merged. For example, this `Description` type, that really should have another name haha, probably something like `LinxMetadata` that better reflects it.

![Captura de Tela 2024-09-02 às 14 14 26](https://github.com/user-attachments/assets/cc0c8122-4e34-4dff-bf69-40fbfa3c0118)

I want to merge all of these types, it will make the development a lot easier, specially when writing Linx type transformations to Schema.org, and overall improve the correctness of our code
