### ISSUE TITLE
Proxy Fails with ?wc-ajax* URLs, Needs Middleware Workaround

### ISSUE THREAD

**Issue by yuriassuncx** [deco-cx/apps#823]
#### Description
When attempting to use a proxy to redirect calls that include the `?` character in the URL, such as `/?wc-ajax*`, the proxy fails to process the request. This issue occurs due to how the `?` character is handled during the construction of the target URL within the proxy.

#### Problem Analysis
The `?` character is a special delimiter in URLs that separates the path from the query parameters. When the target URL is manually constructed, incorrect or redundant addition of `?` can cause issues, especially if:
- The original URL already contains a `?`.
- The query string (`qs`) is empty, leading to an unnecessary `?` at the end of the URL.
- The path (`path`) already includes query parameters.

This led to the need to implement a temporary solution with a separate middleware to handle requests containing `wc-ajax` in the URL. This middleware ensures that the requests are correctly redirected to `https://secure.rosakochen.com.br` with the appropriate headers.

#### Temporary Solution Implemented
A middleware was created to intercept requests containing `wc-ajax` in the URL and construct a new URL using the correct headers. The middleware makes the call directly to the desired URL, ensuring that the request is processed correctly. Here is the middleware code:

```typescript
import { AppMiddlewareContext } from "deco/mod.ts";

const HOP_BY_HOP = [
  "Keep-Alive",
  "Transfer-Encoding",
  "TE",
  "Connection",
  "Trailer",
  "Upgrade",
  "Proxy-Authorization",
  "Proxy-Authenticate",
];

export const handler = async (req: Request, ctx: AppMiddlewareContext) => {
  if (req.url.includes("wc-ajax")) {
    const newUrl = new URL(req.url);
    const headers = new Headers(req.headers);
    HOP_BY_HOP.forEach((h) => headers.delete(h));
    headers.set("origin", "https://secure.rosakochen.com.br");
    headers.set("host", "secure.rosakochen.com.br");
    headers.set("x-forwarded-host", "secure.rosakochen.com.br");
    headers.set("Referer", "https://secure.rosakochen.com.br/checkout/");

    const response = await fetch(
      "https://secure.rosakochen.com.br" + newUrl.search,
      {
        headers,
        method: req.method,
        body: req.body,
      },
    );

    return response;
  }

  return ctx.next!();
};
```

#### Final Considerations
This issue directly impacts the proxy's functionality when handling URLs containing query parameters. The temporary solution with the middleware resolves the specific issue for URLs containing `/?wc-ajax`, but a fix in the main proxy code is necessary to ensure consistent operation in all situations.

**Comment by guitavano** [comment]
Thank you @yuriassuncx.

I am not sure about the solution suggested.

The main problem here is that we want to handler by different ways for the same route, right?

"/" -> Homepage
"/?wc-ajax" -> Proxy

What do you think about use Variants to segment the handler?

**Comment by yuriassuncx** [comment]
> Thank you @yuriassuncx.
> 
> I am not sure about the solution suggested.
> 
> The main problem here is that we want to handler by different ways for the same route, right?
> 
> "/" -> Homepage "/?wc-ajax" -> Proxy
> 
> What do you think about use Variants to segment the handler?


The suggestion doesn't really work. But about using variants to segment the handler, do we have any use cases for this? How can we proceed with the implementation?

**Comment by guitavano** [comment]
> > Thank you @yuriassuncx.
> > I am not sure about the solution suggested.
> > The main problem here is that we want to handler by different ways for the same route, right?
> > "/" -> Homepage "/?wc-ajax" -> Proxy
> > What do you think about use Variants to segment the handler?
> 
> The suggestion doesn't really work. But about using variants to segment the handler, do we have any use cases for this? How can we proceed with the implementation?

I don't think we have this use case yet. @mcandeia can you help us?

Look our [solution](https://github.com/deco-sites/rosakochen/blob/main/routes/_middleware.ts).

How can we do that on routes level? Define a handler if url includes param, and a page without. Even using variants on website app, it runs only once.

**Comment by mcandeia** [comment]
@yuriassuncx can you test this version?  https://github.com/deco-cx/apps/pull/837

Steps to test:

1. Link to this app version
2. Change `extraPathsToProxy` on proxy to include `/?wc-ajax` path.

Done

**Comment by yuriassuncx** [comment]
> @yuriassuncx can you test this version? #837
> 
> Steps to test:
> 
> 1. Link to this app version
> 2. Change `extraPathsToProxy` on proxy to include `/?wc-ajax` path.
> 
> Done

it work for me here, @mcandeia:
[https://github.com/deco-sites/rosakochen/pull/1](https://github.com/deco-sites/rosakochen/pull/1)

**Comment by mcandeia** [comment]
amazing @yuriassuncx, lets proceed @guitavano ?
