### ISSUE TITLE
vary shopify loaders cacheKey based on `filters` querystrings from request URL

### ISSUE THREAD

**Issue by igorbrasileiro** [deco-cx/apps#838]
## Issue Type

Please inform the type(s) of issue(s) you are reporting:

- Bug Report

## Description
The shopify loaders/productListingPage is not varying the cacheKey based on `filters` querystring that comes from URL.

## Steps to Reproduce (for bugs)

1. Go to https://htmx.store/men?sort=price-ascending&page=0
2. Click on `in stock` filter
3. Click on `Out of stock` filter

## Expected Behavior

Change the product list to only have out-of-stock products

## Actual Behavior

It is returning in-stock products.

## Additional Context

The issue happen because the cache key returns the same value, not varying the cache burst (__cb)

---

Thank you for taking the time to report this issue!

**Comment by gustavoberlat** [comment]
I am unable to reproduce the bug in my local environment at 
https://localhost--storefront.deco.site/men?sort=price-ascending&page=0.

Here is a video of my local service running: https://www.loom.com/share/b3308c8320024841890f467d2e07b9ad?sid=33522fa4-b897-4c3c-b159-1b5ba75a103b

Can you provide any help on how to reproduce it?

**Comment by igorbrasileiro** [comment]
Can you try here: https://sites-storefront--issue-838.decocdn.com/men ?

**Comment by matheusgr** [comment]
https://github.com/deco-cx/apps/pull/851
